### ISSUE TITLE
Examples fail on current master 

### ISSUE THREAD

**Issue by raldone01** [danielzfranklin/evdi-rs#16]
commit a1dc5ce79592383180f5fe23385f8a8f2b3ef0c1

```
> ./target/debug/examples/low_level_usage
[libevdi] Wait for master timed out
[libevdi] Opened /dev/dri/card1 as slave drm device
[libevdi] LibEvdi version (1.9.1)
[libevdi] Evdi version (1.13.1)
[libevdi] Using /dev/dri/card1
thread 'main' panicked at 'Timeout waiting for initial ready', examples/low_level_usage.rs:88:13
stack backtrace:
   0: std::panicking::begin_panic
             at /rustc/87b1f891ea76713462cfc5a15137a8fe2b24ecc2/library/std/src/panicking.rs:610:12
   1: low_level_usage::main
             at ./examples/low_level_usage.rs:88:13
   2: core::ops::function::FnOnce::call_once
             at /rustc/87b1f891ea76713462cfc5a15137a8fe2b24ecc2/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

```
> ./target/debug/examples/profile_basic_usage
May 09 11:00:39.520  INFO evdi: libevdi: Wait for master timed out libevdi_unknown_level=true
May 09 11:00:39.521  INFO evdi: libevdi: Opened /dev/dri/card3 as slave drm device libevdi_unknown_level=true
May 09 11:00:39.521  INFO evdi: libevdi: LibEvdi version (1.9.1) libevdi_unknown_level=true
May 09 11:00:39.521  INFO evdi: libevdi: Evdi version (1.13.1) libevdi_unknown_level=true
May 09 11:00:39.521  INFO evdi: libevdi: Using /dev/dri/card3 libevdi_unknown_level=true
May 09 11:00:39.521  INFO evdi::device_node: Opened device 3
May 09 11:00:39.521  INFO connect{self=UnconnectedHandle { device: DeviceNode { id: 3 }, handle: 0x5621eea34010 } config=DeviceConfig { width_pixels: 1920, height_pixels: 1080 }}: evdi::handle: evdi_connect
May 09 11:00:40.525  WARN await_mode{self=HandleEvents timeout=1s}: evdi::events: Timeout awaiting mode: 1s
May 09 11:00:40.525  INFO evdi::handle: evdi_disconnect
May 09 11:00:40.525  INFO evdi: libevdi: Marking /dev/dri/card3 as unused libevdi_unknown_level=true
May 09 11:00:40.525  INFO evdi::handle: evdi_close
May 09 11:00:40.625  WARN evdi::handle: POLLNVAL
Error: Timeout
```

I am running arch linux and have installed `evdi-git`.
I have rebooted.
If I increase the mode timeout to a long time the monitor is recognized and can be shared with `x11vnc` so something works.
It is also recognized by `xrandr`.

**Comment by dzfranklin** [comment]
FYI I'm no longer using this. I have no idea what's going on there except the obvious: that timeout worked on my machine but not yours.

You could try one of the c library examples and see if it takes a while too. It might be that that timeout just needs to be longer?

Good luck

**Comment by raldone01** [comment]
OK thanks. I will try a c library. I tried to increase the timeout but I think it's just stuck endlessly.
